### ISSUE TITLE
[Ubuntu 14] How can I install iTorch if I am using anaconda?

### ISSUE THREAD

**Issue by tohnperfect** [facebook/iTorch#5]
I got the following error when I tried to install iTorch.

Missing dependencies for itorch:
lzmq 
uuid 
lbase64 

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lzmq-0.4.2-1.src.rock... switching to 'build' mode
Archive:  v0.4.2.zip
bb16eda60cd63862f3d1a114229e488bfc43b0d7
   creating: lzmq-0.4.2/
  inflating: lzmq-0.4.2/.gitignore   

.
.
.
Updating manifest for /usr/local/lib/luarocks/rocks
uuid 0.2-1 is now built and installed in /usr/local/ (license: Apache 2.0)

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lbase64-20120820-1.src.rock... switching to 'build' mode
Do not use 'module' as a build type. Use 'builtin' instead.
gcc -O2 -fPIC -I/usr/local/include -c lbase64.c -o lbase64.o
gcc -shared -o base64.so -L/usr/local/lib lbase64.o
Updating manifest for /usr/local/lib/luarocks/rocks
lbase64 20120820-1 is now built and installed in /usr/local/ (license: Public domain)

   ipy=$(which ipython)
   if [ -x "$ipy" ]
   then
	rm -rf ~/.ipython/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/usr/local/bin/itorch_launcher","{connection_file}"]' >>~/.ipython/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>~/.ipython/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>~/.ipython/profile_torch/ipython_config.py
	mkdir -p ~/.ipython/profile_torch/static/base/images
	cp ipynblogo.png ~/.ipython/profile_torch/static/base/images
	mkdir -p ~/.ipython/profile_torch/static/custom/
	cp custom.js ~/.ipython/profile_torch/static/custom/
	cp custom.css ~/.ipython/profile_torch/static/custom/
	cp itorch /usr/local/bin/
	cp itorch_launcher /usr/local/bin/
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi
  

Error: could not find ipython in PATH. Do you have it installed?
cd build && make install
sh: 1: cd: can't cd to build

Error: Build error: Failed installing.

Thank you.

**Comment by soumith** [comment]
simply add the anaconda based python to your path variable. 
Usually anaconda installs everything to ~/anaconda/
so in your terminal, you can add anaconda to the path using:
```bash
export PATH=~/anaconda:$PATH
```
Then you can retry the iTorch install
```bash
luarocks install iTorch
```

**Comment by tohnperfect** [comment]
Thank you but I still got the same error.

**Comment by soumith** [comment]
sorry, i made a mistake in the command above. This is the right one:

export PATH=~/anaconda/bin:$PATH

**Comment by tohnperfect** [comment]
Same error. :'(

**Comment by ajtulloch** [comment]
@tohnperfect, how do you run ipython normally?  Do you specify the path to your ipython binary directly, or is it in your $PATH?

**Comment by tohnperfect** [comment]
just $ipython in the terminal.

**Comment by tohnperfect** [comment]
sorry I'm using Ubuntu 14.04.

**Comment by soumith** [comment]
not able to reproduce this, what is the output of:
```
$ which ipython
```

**Comment by tohnperfect** [comment]
/home/localadmin/anaconda/bin/ipython

**Comment by soumith** [comment]
ok, are you using "luarocks install itorch" or "sudo luarocks install itorch"?

**Comment by tohnperfect** [comment]
I use "sudo ..." because there is a permission problem when I use  "luarocks install itorch".

**Comment by soumith** [comment]
ok that explains everything! phew! I'll update the doc as well, but here is the command that should work:
```bash
sudo -E luarocks make
sudo chown -R $USER ~/.ipython
```

**Comment by soumith** [comment]
you might have to replace $USER with your username

**Comment by tohnperfect** [comment]
I got

 ipy=$(which ipython)
   if [ -x "$ipy" ]
   then
	rm -rf ~/.ipython/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/usr/local/bin/itorch_launcher","{connection_file}"]' >>~/.ipython/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>~/.ipython/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>~/.ipython/profile_torch/ipython_config.py
	mkdir -p ~/.ipython/profile_torch/static/base/images
	cp ipynblogo.png ~/.ipython/profile_torch/static/base/images
	mkdir -p ~/.ipython/profile_torch/static/custom/
	cp custom.js ~/.ipython/profile_torch/static/custom/
	cp custom.css ~/.ipython/profile_torch/static/custom/
	cp itorch /usr/local/bin/
	cp itorch_launcher /usr/local/bin/
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi
  

Error: could not find ipython in PATH. Do you have it installed?
cd build && make install
sh: 1: cd: can't cd to build

Error: Build error: Failed installing.

which is the same error when I input "sudo -E luarocks make"

**Comment by soumith** [comment]
sudo env "PATH=$PATH" luarocks make

this should work. just tested it on ubuntu

**Comment by szagoruyko** [comment]
```sudo env "PATH=$PATH" luarocks make``` doesn't help. I also have the same error on OS X with local install.

**Comment by tohnperfect** [comment]
Many thanks, Soumlth. 
I got this 

   ipy=$(which ipython)
   if [ -x "$ipy" ]
   then
	rm -rf ~/.ipython/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/usr/local/bin/itorch_launcher","{connection_file}"]' >>~/.ipython/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>~/.ipython/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>~/.ipython/profile_torch/ipython_config.py
	mkdir -p ~/.ipython/profile_torch/static/base/images
	cp ipynblogo.png ~/.ipython/profile_torch/static/base/images
	mkdir -p ~/.ipython/profile_torch/static/custom/
	cp custom.js ~/.ipython/profile_torch/static/custom/
	cp custom.css ~/.ipython/profile_torch/static/custom/
	cp itorch /usr/local/bin/
	cp itorch_launcher /usr/local/bin/
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi
  

[ProfileCreate] Generating default config file: u'/home/localadmin/.config/ipython/profile_torch/ipython_config.py'
[ProfileCreate] Generating default config file: u'/home/localadmin/.config/ipython/profile_torch/ipython_qtconsole_config.py'
[ProfileCreate] Generating default config file: u'/home/localadmin/.config/ipython/profile_torch/ipython_notebook_config.py'
[ProfileCreate] Generating default config file: u'/home/localadmin/.config/ipython/profile_torch/ipython_nbconvert_config.py'
sh: 6: cannot create /home/localadmin/.ipython/profile_torch/ipython_config.py: Directory nonexistent
sh: 7: cannot create /home/localadmin/.ipython/profile_torch/ipython_config.py: Directory nonexistent
sh: 8: cannot create /home/localadmin/.ipython/profile_torch/ipython_config.py: Directory nonexistent
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/localadmin/Research/Torch/iTorch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/gfx.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/completer.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/test.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/main.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/Plot.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/_env.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/IOHandler.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/init.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/util.lua
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.js
-- Installing: /usr/local/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.css
Updating manifest for /usr/local/lib/luarocks/rocks
itorch scm-1 is now built and installed in /usr/local/ (license: BSD)

after input "sudo env "PATH=$PATH" luarocks make" which there is the same error at the top but seem to work. I'm not sure.

**Comment by soumith** [comment]
@tohnperfect cheers, it works for you, thanks for being patient.

@szagoruyko the issue seems to be once you enter sudo, 'which ipython' is failing. do you have ipython installed, without sudo, do you see any output on "which ipython"

**Comment by tohnperfect** [comment]
Sorry. It is not working. I got the following error after I try to run "iTorch" in a terminal.

Traceback (most recent call last):
  File "/home/localadmin/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 544, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 312, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 362, in initialize
    self.parse_command_line(argv)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 307, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 474, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 412, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 323, in initialize
    self.init_shell()
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/terminal/console/app.py", line 107, in init_shell
    IPythonConsoleApp.initialize(self)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/consoleapp.py", line 391, in initialize
    self.init_kernel_manager()
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/consoleapp.py", line 347, in init_kernel_manager
    self.kernel_manager.start_kernel(extra_arguments=self.kernel_argv)
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py", line 196, in start_kernel
    self.write_connection_file()
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 478, in write_connection_file
    signature_scheme=self.session.signature_scheme,
  File "/home/localadmin/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 143, in write_connection_file
    with open(fname, 'w') as f:
IOError: [Errno 13] Permission denied: u'/home/localadmin/.config/ipython/profile_torch/security/kernel-10063.json'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by soumith** [comment]
@tohnperfect you did not enter the second command that i specified for sudo, i.e.:
sudo chown -R $USER ~/.ipython

after that this error will disappear

**Comment by tohnperfect** [comment]
I did.

**Comment by soumith** [comment]
oh my bad another wrong command 
Enter this:
sudo chown -R $USER ~/.config

**Comment by soumith** [comment]
there seem to be a couple more issues, looking at your logs. figuring out those.

**Comment by tohnperfect** [comment]
Wow, you guys are incredible. Thank you very for super fast support.
Cheers @soumith

**Comment by tohnperfect** [comment]
Yeah I still suspect there will be some issue because I still get error at the top when I run "sudo env "PATH=$PATH" luarocks make". Anyway If I got more error while I am trying I will report more.

Hope to use iTorch in my project.

Cheers.

**Comment by soumith** [comment]
ok fixed now in trunk

**Comment by soumith** [comment]
these two commands will now work:
```bash
sudo env "PATH=$PATH" luarocks install iTorch
sudo chown -R $USER $(dirname $(ipython locate profile))
```
Also updated the docs to reflect this. 
Let me know if it works.

**Comment by soumith** [comment]
these two commands will now work:
```bash
sudo env "PATH=$PATH" luarocks install itorch
sudo chown -R $USER $(dirname $(ipython locate profile))
```
Also updated the docs to reflect this. 
Let me know if it works.

**Comment by tohnperfect** [comment]
Hi again
I got

  File "<ipython-input-1-d485c9899ef0>", line 1
    require 'image';
                  ^
SyntaxError: invalid syntax

when I input "require 'image';" in the iTorch notebook demo. Any idea? is it related to the error or another issue?

and with the two commands the error still there.

**Comment by soumith** [comment]
looks like it went into ipython, not itorch.
did you start the notebook using:
$ itorch notebook

**Comment by tohnperfect** [comment]
i started with $ iTorch

**Comment by soumith** [comment]
i'm still trying to figure out why this install is so different from what we have on multiple different machines.
what version of ipython are you running?
ipython --version

**Comment by tohnperfect** [comment]
1.1.0

and even with "$ itorch notebook" I still got the same error.

**Comment by soumith** [comment]
oh, it is probably because of that!
we support ipython version 2+. Any modern anaconda install has the updated ipython. please update it.
I will try to put an error check when people have a very old ipython.

**Comment by soumith** [comment]
i think you can update your ipython with 
$conda update ipython

**Comment by szagoruyko** [comment]
no luck for me on Ubuntu, got #6 
so on ubuntu I did these two lines:
```
sudo env "PATH=$PATH" luarocks install itorch
sudo chown -R $USER $(dirname $(ipython locate profile))
```
also tried to rip up rockspec and run parts of it without sudo.
ipython runs normally (version 2.2.0)

on OS X had to add
```
pip install pyzmq
pip install jinja2
```
and it worked.

**Comment by tohnperfect** [comment]
yep updated. I'm trying the demo now.

Though the same error for "sudo env "PATH=$PATH" luarocks install itorch" is still there.

**Comment by tohnperfect** [comment]
I dont think it's working "require 'image';" is running like forever.

**Comment by soumith** [comment]
@tohnperfect what is the error, can you repaste your log this time.
we're finding it hard to reproduce your setup, we've run it on multiple ubuntu machines without issue.

**Comment by tohnperfect** [comment]
yeah sure. How can i get the log?

**Comment by soumith** [comment]
ok great. there is no error in your install whatsoever.

now can you give me the log for:
$ itorch
In [1]: require 'image'
Out[1]:
true

**Comment by tohnperfect** [comment]
I have not got any error but the command is taking like forever.

**Comment by soumith** [comment]
how about:
$ itorch
In [1]: torch.randn(10)

same result, taking forever?

**Comment by soumith** [comment]
if this does not work out, i am sorry, that we cannot reproduce your setup. Try this alternative:
https://github.com/szym/display

**Comment by tohnperfect** [comment]
yes. it's also taking forever.

**Comment by soumith** [comment]
or, maybe try as a fresh user, create a new user on your machine, and try using that user. 
Also, I would suggest reinstalling torch after cleaning up an old install using this script:
https://github.com/torch/ezinstall/blob/master/clean-old.sh

**Comment by tohnperfect** [comment]
OK, I'll try both.

And https://github.com/szym/display is for original torch, isn't it?

**Comment by soumith** [comment]
yes it is another display server, like iTorch or gfx.js

**Comment by tohnperfect** [comment]
Hi, I got it run properly after try installing with fresh user.

I thought my problem is the torch installation because for the old user I could not run "luarocks install image"

Thank you @soumith

**Comment by nicodjimenez** [comment]
I got iTorch to work with my anaconda Python via:
 
mv /usr/local/bin/ipython /usr/local/bin/old_ipython
ln -s /anaconda/bin/ipython /usr/local/bin/ipython

**Comment by chetakks** [comment]
I did change the anaconda python path. even though, the problem exists. Error: could not find ipython in PATH. Do you have it installed?". Kindly clarify how to set path to itorch. I am using ubantu 12.04.

kinect@kinect-System-Product-Name:~/installations/iTorch$ sudo chown -R $USER $(dirname $(ipython locate profile))
kinect@kinect-System-Product-Name:~/installations/iTorch$ sudo env "PATH=$PATH" luarocks make
   ipy=$(which ipython)   
   if [ -x "$ipy" ]
   then
	ipybase=$(ipython locate)
	rm -rf $ipybase/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/usr/local/bin/itorch_launcher","{connection_file}"]' >>$ipybase/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>$ipybase/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>$ipybase/profile_torch/ipython_config.py
	mkdir -p $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/kernels/itorch
	cat kernelspec/kernel.json | sed "s@LUA_BINDIR@/usr/local/bin@" > $ipybase/kernels/itorch/kernel.json
	cp kernelspec/*.png $ipybase/kernels/itorch/
	cp ipynblogo.png $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/profile_torch/static/custom/
	cp custom.js $ipybase/profile_torch/static/custom/
	cp custom.css $ipybase/profile_torch/static/custom/
	cp itorch /usr/local/bin/
	cp itorch_launcher /usr/local/bin/
	cp -r ~/.ipython/profile_torch ~/.ipython/profile_itorch
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi

**Comment by soumith** [comment]
@chetakks the error is not actually printed in your case, it is simply printing out the script it executes to install.

**Comment by chetakks** [comment]
Thanks Soumith, I reinstalled the itorch as per the instructions. The notebook is running, but it is not calling the browser.

kinect@kinect-System-Product-Name:~/installations/iTorch$ sudo chown -R $USER $(dirname $(ipython locate profile))
kinect@kinect-System-Product-Name:~/installations/iTorch$ sudo ./itorch notebook
[I 12:24:13.115 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 12:24:13.127 NotebookApp] Serving notebooks from local directory: /home/kinect/installations/iTorch
[I 12:24:13.127 NotebookApp] 0 active kernels 
[I 12:24:13.127 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 12:24:13.127 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[1:1:0825/122413:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (0 bytes)

**Comment by chetakks** [comment]
Dear Soumith, 

In the iTorch notebook, it says 
"Failed to start the kernel"
"Unknown server error"

The error is Error13, permission denied.

**Comment by chetakks** [comment]
Dear Soumith,

The issue is related to the installation of the python or this is with the
problem of itorch.

kinect@kinect-System-Product-Name:~/installations/iTorch$ sudo ./itorch
notebook[I 15:19:14.291 NotebookApp] Using MathJax from CDN:
https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 15:19:14.303 NotebookApp] Serving notebooks from local directory:
/home/kinect/installations/iTorch
[I 15:19:14.303 NotebookApp] 0 active kernels
[I 15:19:14.303 NotebookApp] The IPython Notebook is running at:
http://localhost:8888/
[I 15:19:14.303 NotebookApp] Use Control-C to stop this server and shut
down all kernels (twice to skip confirmation).
[1:1:0826/151914:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper
startup ack (0 bytes)
